[workspace]
members = [
    "crates/lmprk-core",
    "crates/lmprk-verifier",
    "crates/lmprk-rpc",
]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2021"
license = "MIT"
authors = ["lmprk-labs"]
repository = "https://github.com/lmprk-labs/lmprk"
homepage = "https://lmprk.fun"

[workspace.dependencies]
blake3 = "1.5"
ed25519-dalek = { version = "2.1", default-features = false, features = ["alloc", "rand_core"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
bs58 = "0.5"
hex = "0.4"
rand_core = { version = "0.6", features = ["std"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
